### ISSUE TITLE
Suggested improvements in Sass

### ISSUE THREAD

**Issue by akfzambrana** [tiagoporto/swill-boilerplate#17]
Hi @tiagoporto, I want to help you with some improvements in your Sass functions and helpers.

I forked your project already and I'll create a PR with my suggestions but I've a doubt:
- Why are you using both sass extensions? I refer to sass and scss extensions in the same project

It's better to choose one and keep it.

**Comment by tiagoporto** [comment]
Hello @akfzambrana, do you speak portugues?

**Comment by akfzambrana** [comment]
Opa! claro :wink: 
(foi mal, é que vi o repositorio em ingles e utilizei ele na issue)

**Comment by tiagoporto** [comment]
Quem bom, assim fica mais fácil te responde claramente.
Particularmente prefiro o uso do `.sass`, mas a grande maioria das pessoas usa `.scss`. O bacana que o SASS compila os 2. Como estou trabalhando muito mais com o Stylus acabei não evoluindo a parte do SASS. É uma boa observação, quem sabe você não me ajuda a padronizar? :)

Ainda quero fazer um port das funcionalidades que estão no Stylus para o SASS, mas falta tempo.

**Comment by akfzambrana** [comment]
vou dar uma olhada no que tem em Stylus e tentar te ajudar, vou manter então a sintaxe scss que é a mais utilizada pela galera e que fica mais facil de entender. Vou fazer o fork então do seu outro projeto e ajudar naquele. :kissing_heart:

**Comment by tiagoporto** [comment]
Que ótimo, obrigado.
