### ISSUE TITLE
Suggested improvements in Sass

### ISSUE THREAD

**Issue by akfzambrana** [tiagoporto/swill-boilerplate#18]
Hi @tiagoporto, I want to help you with some improvements in your Sass functions and helpers.

I forked your project already and I'll create a PR with my suggestions but I've a doubt:
- Why are you using both sass extensions? I refer to sass and scss extensions in the same project

It's better to choose one and keep it.

Which one you'll prefer to use?

**Comment by tiagoporto** [comment]
#17

**Comment by tiagoporto** [comment]
#17

**Comment by tiagoporto** [comment]
#17
